In [1]:
import torch
torch.__version__

'2.9.0+cpu'

In [2]:
# A scalar has a dimension of 0
scalar= torch.tensor(5)
scalar

tensor(5)

In [3]:
#ndim allows us to see the dimension of a tensor (and it is like attribute) while .item() shows the value
print (scalar.ndim)
print(scalar.item())

0
5


In [4]:
# A vector has a single dimension which is usualy enclosed under a sing bracket like [] and can have an arbitrary number of elements
vector= torch.tensor([1,2,3,4])
print(vector.ndim)
# print(vector.item()) -- you can not do like this because items is for scalars only

1


In [5]:
# for dimension of tensors we count the depth of the tensor and this is done by counting open brackets until you hit the first closing bracket
MTX0= torch.tensor([[1,2], [5,3]])
MTX0.ndim

2

In [6]:
#for shape of tensors (which shows the size) first we can learn from the dimension how much number we are going to have like 
# for a dimension of 1 you can only have one number and  for a dimension of 2 you can have two numbers
# then we count rows and put number of rows until we reach the inner most which we then put the number of columns
MTX1= torch.tensor([[1,2], [5,3]])
MTX1.shape

torch.Size([2, 2])

In [7]:
# Now try to answer the following ones:

tensor1 = torch.tensor(42)
print("Tensor1:", tensor1)
print("Tensor1 ndim:", tensor1.ndim)   # your guess: 
print("Tensor1 shape:", tensor1.shape) # your guess: 
print("-"*40)


Tensor1: tensor(42)
Tensor1 ndim: 0
Tensor1 shape: torch.Size([])
----------------------------------------


In [8]:

tensor2 = torch.tensor([10, 20, 30, 40])
print("Tensor2:", tensor2)
print("Tensor2 ndim:", tensor2.ndim)   # your guess: 
print("Tensor2 shape:", tensor2.shape) # your guess: 
print("-"*40)

Tensor2: tensor([10, 20, 30, 40])
Tensor2 ndim: 1
Tensor2 shape: torch.Size([4])
----------------------------------------


In [9]:
tensor3 = torch.tensor([[1,2,3],[4,5,6]])
print("Tensor3:", tensor3)
print("Tensor3 ndim:", tensor3.ndim)   # your guess: 
print("Tensor3 shape:", tensor3.shape) # your guess: 
print("-"*40)

Tensor3: tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor3 ndim: 2
Tensor3 shape: torch.Size([2, 3])
----------------------------------------


In [10]:

tensor4 = torch.tensor([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]],
    [[13,14],[15,16],[17,18]]
])
print("Tensor4:", tensor4)
print("Tensor4 ndim:", tensor4.ndim)   # your guess: 
print("Tensor4 shape:", tensor4.shape) # your guess: 
print("-"*40)

Tensor4: tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]])
Tensor4 ndim: 3
Tensor4 shape: torch.Size([3, 3, 2])
----------------------------------------


In [11]:

tensor5 = torch.tensor([])
print("Tensor5:", tensor5)
print("Tensor5 ndim:", tensor5.ndim)   # your guess: 
print("Tensor5 shape:", tensor5.shape) # your guess: 
print("-"*40)

Tensor5: tensor([])
Tensor5 ndim: 1
Tensor5 shape: torch.Size([0])
----------------------------------------


In [12]:

tensor6 = torch.tensor([[1],[2],[3],[4],[5]])
print("Tensor6:", tensor6)
print("Tensor6 ndim:", tensor6.ndim)   # your guess: 
print("Tensor6 shape:", tensor6.shape) # your guess: 
print("-"*40)

Tensor6: tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Tensor6 ndim: 2
Tensor6 shape: torch.Size([5, 1])
----------------------------------------


In [13]:

tensor7 = torch.tensor([[10,20,30,40,50]])
print("Tensor7:", tensor7)
print("Tensor7 ndim:", tensor7.ndim)   # your guess: 
print("Tensor7 shape:", tensor7.shape) # your guess: 
print("-"*40)

Tensor7: tensor([[10, 20, 30, 40, 50]])
Tensor7 ndim: 2
Tensor7 shape: torch.Size([1, 5])
----------------------------------------


In [14]:

tensor8 = torch.tensor([
    [[[1,2],[3,4]],[[5,6],[7,8]]],
    [[[9,10],[11,12]],[[13,14],[15,16]]]
])
print("Tensor8:", tensor8)
print("Tensor8 ndim:", tensor8.ndim)   # your guess: 
print("Tensor8 shape:", tensor8.shape) # your guess: 
print("-"*40)

Tensor8: tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Tensor8 ndim: 4
Tensor8 shape: torch.Size([2, 2, 2, 2])
----------------------------------------


In [15]:

tensor9 = torch.tensor([999])
print("Tensor9:", tensor9)
print("Tensor9 ndim:", tensor9.ndim)   # your guess: 
print("Tensor9 shape:", tensor9.shape) # your guess: 
print("-"*40)


Tensor9: tensor([999])
Tensor9 ndim: 1
Tensor9 shape: torch.Size([1])
----------------------------------------


In [16]:

tensor10 = torch.tensor([
    [[1,2,3,4]],
    [[5,6,7,8]],
    [[9,10,11,12]]
])
print("Tensor10:", tensor10)
print("Tensor10 ndim:", tensor10.ndim)   # your guess: 
print("Tensor10 shape:", tensor10.shape) # your guess: 
print("-"*40)

Tensor10: tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])
Tensor10 ndim: 3
Tensor10 shape: torch.Size([3, 1, 4])
----------------------------------------


In [17]:
#for  generating random tensors
MTX2=torch.rand(size=(2,3))
MTX2, MTX2.ndim

(tensor([[0.6734, 0.4929, 0.2699],
         [0.4113, 0.2068, 0.5279]]),
 2)

In [18]:
#for generating tensors filled with 0's
MTX3= torch.zeros(size=(1,3))
MTX3, MTX3.ndim

(tensor([[0., 0., 0.]]), 2)

In [19]:
#for generating tensors filled with 1's
MTX4= torch.ones(size=(2,1))
MTX4, MTX4.ndim

(tensor([[1.],
         [1.]]),
 2)

In [20]:
#for generating tensors in a range with start and end
MTX5= torch.range(0,8)
MTX5, MTX5.ndim

/tmp/ipython-input-3210452060.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  MTX5= torch.range(0,8)


(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]), 1)

In [21]:
#for generating tensors in a ragne but with step value too (which is specified at the end)
MTX6= torch.arange(2, 15, 3)
MTX6, MTX6.ndim

(tensor([ 2,  5,  8, 11, 14]), 1)

In [22]:
# TO SEE THE DATA TYPE OF THE TENSORS WE CAN USE .dtype which acts as an attribute
MTX6.dtype

torch.int64

In [23]:
# There are a lot of datatypes
# torch.float  with different levels of precision like torch.float8, torch.float16, torch.float32, torch.float64
# torch.int with different size and signs like torch.int8, torch.int16, torch.int32 , torch.int64
# torch.bool

In [24]:
# device attribute indicates what we are using for the executing: cpu, gpu
# cuda is for gpu
# by default we run on cpu

In [25]:
float_32_tensor= torch.tensor([4.0, 6.0], device=None, dtype=torch.float64, requires_grad=False)
float_32_tensor

tensor([4., 6.], dtype=torch.float64)

In [26]:
# to check if cuda is available
print(torch.cuda.is_available())

False


In [27]:
# one of the most used  tools for getting information about a tensor are shape, dtype and device
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.3951, 0.9630, 0.9416, 0.0924],
        [0.2698, 0.5099, 0.6711, 0.2456],
        [0.0491, 0.9629, 0.0044, 0.7001]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [35]:
# Manipulating tensors
# basic operations
#Addition
MTX7= torch.tensor([[2,3,4], [1,7,8]])  #shape of [2,3]
#Rule 1: simple scalar addition (it works for and shape)
res1= MTX7 + 10
print("Simple scalar addition: ",res2)
#Rule 2: when tensors have the same shape
MTX8= torch.rand(size=(2,3))
RS1= MTX7 + MTX8
print("The same shape tensor addition: " ,RS1)
# Broadcasting rule: Starting from the rightmost dimension, compare shapes:
# For each dimension: if equal or one of them is 1 then addition works
#lets generate a tensor that fulfils this
MTX9= torch.tensor([[2,5,8]]) #shape [1, 3]
RS2= MTX7 + MTX9
print ("Broadcast additon example result: ", RS2)


Simple scalar addition:  tensor([[20, 30, 40],
        [10, 70, 80]])
The same shape tensor addition:  tensor([[2.7595, 3.4147, 4.6119],
        [1.8587, 7.4450, 8.2923]])
Broadcast additon example result:  tensor([[ 4,  8, 12],
        [ 3, 12, 16]])


In [38]:
# Element wise MULTIPLICATION
res2= MTX7 * 10 
print("Simple scalar multiplication: ", res2)
# For others it follows the same rules as additon , it is multipliable if they have teh same shape or if it is brodcastible
RS3 = MTX7 * MTX8
print("same shape multiplication: ", RS3)
RS4 = MTX7 * MTX9
print("Brodcast multiplication rule result: ", RS4)

Simple scalar multiplication:  tensor([[20, 30, 40],
        [10, 70, 80]])
same shape multiplication:  tensor([[1.5191, 1.2441, 2.4477],
        [0.8587, 3.1147, 2.3381]])
Brodcast multiplication rule result:  tensor([[ 4, 15, 32],
        [ 2, 35, 64]])


In [ ]:
# Matrix multiplication
# For matrix multiplication to work the inner dimensions must match. the result of such multiplication has the shape of the outer dimensions
MTX10= torch.tensor([[1,3,4], [2,5,1]]) #shape [2, 3]
MTX11= torch.tensor([[2, 1], [4,2], [5,3]]) #shape [3, 2]
# the above two tensor inner dimensions are 3 and 3 which is the last for the fist tensor and the first for the second tensor
# Now since their inner dimensions match it works and the result will have a dimension of [2,2]
RS5= MTX10 @ MTX11  # @ is matrix multiplication, we can use torch.matmul() too
print("Result of matrix multiplication using '@': ", RS5)
RS6= torch.matmul(MTX10, MTX11)  # a shortcut to this is torch.mm(MTX10 , MTX11)
print("Result of matrix multiplication using torch.matmul() : ", RS6)

Result of matrix multiplication using '@':  tensor([[34, 19],
        [29, 15]])
Result of matrix multiplication using torch.matmul() :  tensor([[34, 19],
        [29, 15]])


In [ ]:
# Subtraction , it is exactly the same as addition interms of the rules like brodcast and others
res3= MTX7 - 5
res3

tensor([[-3, -2, -1],
        [-4,  2,  3]])

In [ ]:
# Division / follows exactly the same broadcasting rules as + - *
# In an element wise divison same shape, broadcasting and scalar work
# It is important to note that there is not matrix division , it is only element wise so no other rules like inner dimensions must match
res4= MTX7 / 2
res4

tensor([[1.0000, 1.5000, 2.0000],
        [0.5000, 3.5000, 4.0000]])

In [47]:
# Transposition
MTX12= torch.tensor([[2,1,8], [4,7,3]])
#Since the above tensor is of 2 dimension we can do 
print(MTX12.T)
# but if it was  another higher dimension it wont work so what we use is
transposed_MTX12= MTX12.transpose(0, 1) # we use python indexing which starts from 0 but also pytorch uses negative indices ( it is better to use .T for 2 dimensions)
print("Transposed matrix (how we do it for higher dimensions): ", transposed_MTX12)
#for higher dimensions
x = torch.randn(2,3,4,5)  # shape [2,3,4,5]

# Swap last two dimensions
y = x.transpose(-2,-1)  
print(y.shape)  # [2,3,5,4]

tensor([[2, 4],
        [1, 7],
        [8, 3]])
Transposed matrix (how we do it for higher dimensions):  tensor([[2, 4],
        [1, 7],
        [8, 3]])
torch.Size([2, 3, 5, 4])
