In [1]:
import torch
torch.__version__

'2.9.0+cu128'

In [ ]:
# A scalar has a dimension of 0
scalar= torch.tensor(5)
scalar

tensor(5)

In [ ]:
#ndim allows us to see the dimension of a tensor (and it is like attribute) while .item() shows the value
print (scalar.ndim)
print(scalar.item())

0
5


In [ ]:
# A vector has a single dimension which is usualy enclosed under a sing bracket like [] and can have an arbitrary number of elements
vector= torch.tensor([1,2,3,4])
print(vector.ndim)
# print(vector.item()) -- you can not do like this because items is for scalars only

1


In [ ]:
# for dimension of tensors we count the depth of the tensor and this is done by counting open brackets until you hit the first closing bracket
MTX0= torch.tensor([[1,2], [5,3]])
MTX0.ndim

2

In [6]:
#for shape of tensors (which shows the size) first we can learn from the dimension how much number we are going to have like 
# for a dimension of 1 you can only have one number and  for a dimension of 2 you can have two numbers
# then we count rows and put number of rows until we reach the inner most which we then put the number of columns
MTX1= torch.tensor([[1,2], [5,3]])
MTX1.shape

torch.Size([2, 2])

In [7]:
# Now try to answer the following ones:

tensor1 = torch.tensor(42)
print("Tensor1:", tensor1)
print("Tensor1 ndim:", tensor1.ndim)   # your guess: 
print("Tensor1 shape:", tensor1.shape) # your guess: 
print("-"*40)


Tensor1: tensor(42)
Tensor1 ndim: 0
Tensor1 shape: torch.Size([])
----------------------------------------


In [ ]:

tensor2 = torch.tensor([10, 20, 30, 40])
print("Tensor2:", tensor2)
print("Tensor2 ndim:", tensor2.ndim)   # your guess: 
print("Tensor2 shape:", tensor2.shape) # your guess: 
print("-"*40)

Tensor2: tensor([10, 20, 30, 40])
Tensor2 ndim: 1
Tensor2 shape: torch.Size([4])
----------------------------------------


In [9]:
tensor3 = torch.tensor([[1,2,3],[4,5,6]])
print("Tensor3:", tensor3)
print("Tensor3 ndim:", tensor3.ndim)   # your guess: 
print("Tensor3 shape:", tensor3.shape) # your guess: 
print("-"*40)

Tensor3: tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor3 ndim: 2
Tensor3 shape: torch.Size([2, 3])
----------------------------------------


In [ ]:

tensor4 = torch.tensor([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]],
    [[13,14],[15,16],[17,18]]
])
print("Tensor4:", tensor4)
print("Tensor4 ndim:", tensor4.ndim)   # your guess: 
print("Tensor4 shape:", tensor4.shape) # your guess: 
print("-"*40)

Tensor4: tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]])
Tensor4 ndim: 3
Tensor4 shape: torch.Size([3, 3, 2])
----------------------------------------


In [ ]:

tensor5 = torch.tensor([])
print("Tensor5:", tensor5)
print("Tensor5 ndim:", tensor5.ndim)   # your guess: 
print("Tensor5 shape:", tensor5.shape) # your guess: 
print("-"*40)

Tensor5: tensor([])
Tensor5 ndim: 1
Tensor5 shape: torch.Size([0])
----------------------------------------


In [ ]:

tensor6 = torch.tensor([[1],[2],[3],[4],[5]])
print("Tensor6:", tensor6)
print("Tensor6 ndim:", tensor6.ndim)   # your guess: 
print("Tensor6 shape:", tensor6.shape) # your guess: 
print("-"*40)

Tensor6: tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Tensor6 ndim: 2
Tensor6 shape: torch.Size([5, 1])
----------------------------------------


In [ ]:

tensor7 = torch.tensor([[10,20,30,40,50]])
print("Tensor7:", tensor7)
print("Tensor7 ndim:", tensor7.ndim)   # your guess: 
print("Tensor7 shape:", tensor7.shape) # your guess: 
print("-"*40)

Tensor7: tensor([[10, 20, 30, 40, 50]])
Tensor7 ndim: 2
Tensor7 shape: torch.Size([1, 5])
----------------------------------------


In [ ]:

tensor8 = torch.tensor([
    [[[1,2],[3,4]],[[5,6],[7,8]]],
    [[[9,10],[11,12]],[[13,14],[15,16]]]
])
print("Tensor8:", tensor8)
print("Tensor8 ndim:", tensor8.ndim)   # your guess: 
print("Tensor8 shape:", tensor8.shape) # your guess: 
print("-"*40)

Tensor8: tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Tensor8 ndim: 4
Tensor8 shape: torch.Size([2, 2, 2, 2])
----------------------------------------


In [ ]:

tensor9 = torch.tensor([999])
print("Tensor9:", tensor9)
print("Tensor9 ndim:", tensor9.ndim)   # your guess: 
print("Tensor9 shape:", tensor9.shape) # your guess: 
print("-"*40)


Tensor9: tensor([999])
Tensor9 ndim: 1
Tensor9 shape: torch.Size([1])
----------------------------------------


In [ ]:

tensor10 = torch.tensor([
    [[1,2,3,4]],
    [[5,6,7,8]],
    [[9,10,11,12]]
])
print("Tensor10:", tensor10)
print("Tensor10 ndim:", tensor10.ndim)   # your guess: 
print("Tensor10 shape:", tensor10.shape) # your guess: 
print("-"*40)

Tensor10: tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])
Tensor10 ndim: 3
Tensor10 shape: torch.Size([3, 1, 4])
----------------------------------------


In [17]:
#for  generating random tensors
MTX2=torch.rand(size=(2,3))
MTX2, MTX2.ndim

(tensor([[0.9491, 0.6899, 0.4748],
         [0.0495, 0.6998, 0.0589]]),
 2)

In [ ]:
#for generating tensors filled with 0's
MTX3= torch.zeros(size=(1,3))
MTX3, MTX3.ndim

(tensor([[0., 0., 0.]]), 2)

In [19]:
#for generating tensors filled with 1's
MTX4= torch.ones(size=(2,1))
MTX4, MTX4.ndim

(tensor([[1.],
         [1.]]),
 2)

In [20]:
#for generating tensors in a range with start and end
MTX5= torch.range(0,8)
MTX5, MTX5.ndim

/tmp/ipython-input-3210452060.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  MTX5= torch.range(0,8)


(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]), 1)

In [ ]:
#for generating tensors in a ragne but with step value too (which is specified at the end)
MTX6= torch.arange(2, 15, 3)
MTX6, MTX6.ndim

(tensor([ 2,  5,  8, 11, 14]), 1)

In [ ]:
# TO SEE THE DATA TYPE OF THE TENSORS WE CAN USE .dtype which acts as an attribute
MTX6.dtype

torch.int64

In [ ]:
# There are a lot of datatypes
# torch.float  with different levels of precision like torch.float8, torch.float16, torch.float32, torch.float64
# torch.int with different size and signs like torch.int8, torch.int16, torch.int32 , torch.int64
# torch.bool

In [24]:
# device attribute indicates what we are using for the executing: cpu, gpu
# cuda is for gpu
# by default we run on cpu

In [ ]:
float_32_tensor= torch.tensor([4.0, 6.0], device=None, dtype=torch.float64, requires_grad=False)
float_32_tensor

tensor([4., 6.], dtype=torch.float64)

In [ ]:
# to check if cuda is available
print(torch.cuda.is_available())

True


In [ ]:
# one of the most used  tools for getting information about a tensor are shape, dtype and device
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.4727, 0.0134, 0.3407, 0.7281],
        [0.8278, 0.3709, 0.0971, 0.5266],
        [0.7118, 0.3000, 0.3832, 0.0333]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# Manipulating tensors
# basic operations
#Addition
MTX7= torch.tensor([[2,3,4], [1,7,8]])  #shape of [2,3]
#Rule 1: simple scalar addition (it works for and shape)
res1= MTX7 + 10
print("Simple scalar addition: ",res1)
#Rule 2: when tensors have the same shape
MTX8= torch.rand(size=(2,3))
RS1= MTX7 + MTX8
print("The same shape tensor addition: " ,RS1)
# Broadcasting rule: Starting from the rightmost dimension, compare shapes:
# For each dimension: if equal or one of them is 1 then addition works
#lets generate a tensor that fulfils this
MTX9= torch.tensor([[2,5,8]]) #shape [1, 3]
RS2= MTX7 + MTX9
print ("Broadcast additon example result: ", RS2)


Simple scalar addition:  tensor([[12, 13, 14],
        [11, 17, 18]])
The same shape tensor addition:  tensor([[2.9310, 3.6624, 4.8638],
        [1.5799, 7.3753, 8.4049]])
Broadcast additon example result:  tensor([[ 4,  8, 12],
        [ 3, 12, 16]])


In [ ]:
# Element wise MULTIPLICATION
res2= MTX7 * 10 
print("Simple scalar multiplication: ", res2)
# For others it follows the same rules as additon , it is multipliable if they have teh same shape or if it is brodcastible
RS3 = MTX7 * MTX8
print("same shape multiplication: ", RS3)
RS4 = MTX7 * MTX9
print("Brodcast multiplication rule result: ", RS4)

Simple scalar multiplication:  tensor([[20, 30, 40],
        [10, 70, 80]])
same shape multiplication:  tensor([[1.8619, 1.9873, 3.4553],
        [0.5799, 2.6271, 3.2394]])
Brodcast multiplication rule result:  tensor([[ 4, 15, 32],
        [ 2, 35, 64]])


In [ ]:
# Matrix multiplication
# For matrix multiplication to work the inner dimensions must match. the result of such multiplication has the shape of the outer dimensions
MTX10= torch.tensor([[1,3,4], [2,5,1]]) #shape [2, 3]
MTX11= torch.tensor([[2, 1], [4,2], [5,3]]) #shape [3, 2]
# the above two tensor inner dimensions are 3 and 3 which is the last for the fist tensor and the first for the second tensor
# Now since their inner dimensions match it works and the result will have a dimension of [2,2]
RS5= MTX10 @ MTX11  # @ is matrix multiplication, we can use torch.matmul() too
print("Result of matrix multiplication using '@': ", RS5)
RS6= torch.matmul(MTX10, MTX11)  # a shortcut to this is torch.mm(MTX10 , MTX11)
print("Result of matrix multiplication using torch.matmul() : ", RS6)

Result of matrix multiplication using '@':  tensor([[34, 19],
        [29, 15]])
Result of matrix multiplication using torch.matmul() :  tensor([[34, 19],
        [29, 15]])


In [ ]:
# Subtraction , it is exactly the same as addition interms of the rules like brodcast and others
res3= MTX7 - 5
res3

tensor([[-3, -2, -1],
        [-4,  2,  3]])

In [ ]:
# Division / follows exactly the same broadcasting rules as + - *
# In an element wise divison same shape, broadcasting and scalar work
# It is important to note that there is not matrix division , it is only element wise so no other rules like inner dimensions must match
res4= MTX7 / 2
res4

tensor([[1.0000, 1.5000, 2.0000],
        [0.5000, 3.5000, 4.0000]])

In [ ]:
# Transposition
MTX12= torch.tensor([[2,1,8], [4,7,3]])
#Since the above tensor is of 2 dimension we can do 
print(MTX12.T)
# but if it was  another higher dimension it wont work so what we use is
transposed_MTX12= MTX12.transpose(0, 1) # we use python indexing which starts from 0 but also pytorch uses negative indices ( it is better to use .T for 2 dimensions)
print("Transposed matrix (how we do it for higher dimensions): ", transposed_MTX12)
#for higher dimensions
x = torch.randn(2,3,4,5)  # shape [2,3,4,5]

# Swap last two dimensions
y = x.transpose(-2,-1)  
print(y.shape)  # [2,3,5,4]

tensor([[2, 4],
        [1, 7],
        [8, 3]])
Transposed matrix (how we do it for higher dimensions):  tensor([[2, 4],
        [1, 7],
        [8, 3]])
torch.Size([2, 3, 5, 4])


In [ ]:
# Aggregation operations
# min, max, mean , sum
MXT13= torch.arange(3,19,2)
print("MXT13: ", MXT13)
print("Minimum value is: ", MXT13.min())
print("Maximum value is: ", MXT13.max())
print("Total sum results in to: ", MXT13.sum())
print()

MXT13:  tensor([ 3,  5,  7,  9, 11, 13, 15, 17])
Minimum value is:  tensor(3)
Maximum value is:  tensor(17)
Total sum results in to:  tensor(80)



In [ ]:
#Now for mean it is a little different as it involves dividing and this causes change in data type
print("Mean value is: ", MXT13.to(torch.float32).mean())

Mean value is:  tensor(10.)


In [36]:
# So if the tensor is already in a floating point data type there is no need to convert it first
MXT14= torch.arange(3,19,2, dtype=torch.float32)
print("The mean value for an already floting data type tensor is: ", MXT14.mean())

The mean value for an already floting data type tensor is:  tensor(10.)


In [37]:
# We can also find where the minimum and maxium values occur (index)
# we use argmin and argmax 
MXT15=torch.tensor([2, 9,11,0, 15,18,3,6])
print("The minimum value of this tensor occurs at: ", MXT15.argmin())
print("The maximum value occurs at index: ", MXT15.argmax())

The minimum value of this tensor occurs at:  tensor(3)
The maximum value occurs at index:  tensor(5)


In [ ]:
# Changing tensor data type
MXT16= torch.arange(0, 9, 2)
print("datatype initially: ", MXT16.dtype)
MXT16prime= MXT16.type(torch.float32)
print("Data type of the new drived tensor: ", MXT16prime.dtype)


datatype initially:  torch.int64
Data type of the new drived tensor:  torch.float32


Can Any Numeric Tensor Type Be Changed to Another?

Yes, numeric tensor types (float, int, etc.) can be converted to other numeric types.

But the values may change due to:

Precision loss (smaller floats)

Truncation (float → int)

Overflow (large values into small integer types)

Integer tensors cannot be used for gradient-based training.

In [ ]:
# Reshape, stack, squeeze, unsqueeze,
# reshape
x= torch.arange(1.0, 7.0)
print("shape: ", x,  x.shape)
x_reshaped= x.reshape(1,6) # The inputs represent the dimension of the new tensor we want to create
print("shape: ", x_reshaped,  x_reshaped.shape)

x_reshaped= x.reshape(6,1)
print("shape: ", x_reshaped,  x_reshaped.shape)
print("***************************************************")
# we can also let it figure out the dimension , you do this by setting -1
x_reshaped= x.reshape(1, -1)
print("shape: ", x_reshaped,  x_reshaped.shape)

shape:  tensor([1., 2., 3., 4., 5., 6.]) torch.Size([6])
shape:  tensor([[1., 2., 3., 4., 5., 6.]]) torch.Size([1, 6])
shape:  tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]]) torch.Size([6, 1])
***************************************************
shape:  tensor([[1., 2., 3., 4., 5., 6.]]) torch.Size([1, 6])


In [ ]:
# Stacking means combining multiple tensors along a new dimension.
# You have multiple tensors of the same shape. You want to join them into one bigger tensor. Unlike concatenation, stacking always creates a new dimension.
# The requirement for stacking is all tensors must have the same shape.
a= torch.tensor([1,2,3])
b= torch.tensor([4,5,6])
stacked= torch.stack((a,b), dim=1) # we can also use dim=0 here
print(stacked, stacked.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2])


In [ ]:
#Squeeze is used to remove all 1 dimensions in a tensor
a= torch.tensor([[1,2,3]])
print("a shape: ", a.shape)
print("when squeezing: ", a.squeeze(), a.squeeze().shape)


a shape:  torch.Size([1, 3])
when squeezing:  tensor([1, 2, 3]) torch.Size([3])


In [ ]:
# To do the reverse of squeeze we use unsqueeze
print(f"a: {a}  shape: {a.shape}")
print(f"a unsqueezed: {a.unsqueeze(0)}  shape: {a.unsqueeze(0).shape}") # what makes it different is you get to specify on which dimension to add it
print(f"a unsqueezed dim 1: {a.unsqueeze(1)}  shape: {a.unsqueeze(1).shape}")
print(f"a unsqueezed dim 2: {a.unsqueeze(2)}  shape: {a.unsqueeze(2).shape}")

a: tensor([[1, 2, 3]])  shape: torch.Size([1, 3])
a unsqueezed: tensor([[[1, 2, 3]]])  shape: torch.Size([1, 1, 3])
a unsqueezed dim 1: tensor([[[1, 2, 3]]])  shape: torch.Size([1, 1, 3])
a unsqueezed dim 2: tensor([[[1],
         [2],
         [3]]])  shape: torch.Size([1, 3, 1])


In [ ]:
# permute is used for reordering the dimension of tensors
x= torch.tensor([[1,2,3], [4,5,6]])
y= x.permute(1,0) # this swaps row with column
print("x: " , x)
print("y: " , y)

x:  tensor([[1, 2, 3],
        [4, 5, 6]])
y:  tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
a = torch.arange(24).reshape(2, 3, 4)
print("a: ",a, a.shape)

a:  tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4])


In [ ]:
print("a permute along  2,0,1: ", a.permute(2,0,1), a.permute(2,0,1).shape)
# 2 indicates  the third dimension (which was 4) so now we will have 4 rows at the higher level
# 0 indicates the first dimension which was 2, so now we will have another 2 rows inside of those 4 rows
# 1 indicates the second dimension which was 3 will now show the columns which there will be 3 columns

a permute along  2,0,1:  tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]]) torch.Size([4, 2, 3])


In [ ]:
#Indexing
x= torch.tensor([[1,2,3], [4,5,6]])
print(x[0]) # this will print the first row
print(x[0][1]) # this will pring the first row second column
print(x[:,0])
# : → means take all elements along this dimension (so for the above example we consider all rows)
#0 → take index 0 along the second dimension (dim 1, columns)   (so for the above example we will take the first element of all rows)


tensor([1, 2, 3])
tensor(2)
tensor([1, 4])


In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x.shape)
print(x[:,:,:1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[[1],
         [4],
         [7]]])


In [ ]:
# PyTorch tensors & NumPy
#torch.from_numpy()
#torch.Tensor.numpy()

In [49]:
import numpy as np

a= np.arange(1,10)
p= torch.from_numpy(a)
a, p

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
tnsor= torch.tensor([1,2,3,4,5,6])
numpy_array= tnsor.numpy()
tnsor, numpy_array

(tensor([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [51]:
# randomness and ensurring reproducability
rndm1= torch.rand(3) # if we just put a number inside it will generate a dim 1 tensor with the quantity of random numbers you specified
print(rndm1)
rndm2= torch.rand(2,3) # now this will create a tensor with shape [2,3]
print(rndm2)
rndm3= torch.rand(2,3)
print(rndm3) # rndm3 and rndm2 have been generated the same way but they are different because we used rand
print("***********************************************************")
#But what if we want to get the same generated random number, for reproducibility
#for such cases we use torch.manual_seed() and it takes any number and aslong as we use that seed we get the same result
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
rndm4= torch.rand(2,3)
torch.manual_seed(RANDOM_SEED)
rndm5= torch.rand(2,3)
print("rndm4: ",rndm4)
print("rndm5: ",rndm5)

tensor([0.1401, 0.8419, 0.2550])
tensor([[0.5208, 0.8659, 0.8480],
        [0.4947, 0.9785, 0.1366]])
tensor([[0.0124, 0.5062, 0.9418],
        [0.7618, 0.0990, 0.7127]])
***********************************************************
rndm4:  tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
rndm5:  tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [54]:
# Here we will see how to use GPU
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1


In [57]:
#this shows creating a tensor for cuda/gpu
a= torch.tensor([11,23,43,10] , device="cuda:0")
print(a, a.device)
# we can also change tensors from one device to another
b= a.to("cpu")
print(b, b.device)

tensor([11, 23, 43, 10], device='cuda:0') cuda:0
tensor([11, 23, 43, 10]) cpu
